name: automaster
version: 1.0.0+2
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.3+1
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  fl_chart: ^0.68.0

flutter:
  uses-material-design: true
